name: Generate Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *"   # runs once a day
  workflow_dispatch:        # lets you also run it manually
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: Deepa5270
          theme: github_dark
